openapi: 3.0.0
info:
  title: BCDice API
  version: '1.0'
  description: BCDiceのWeb API
  contact:
    name: BCDice Discordサーバ
    url: 'https://discord.gg/x5MMKWA'
  license:
    name: MIT
    url: 'https://github.com/ysakasin/bcdice-api/blob/master/LICENSE'
servers:
  - url: '{server}/v1'
    variables:
      server:
        description: BCDice APIサーバ
        default: 'https://bcdice.herokuapp.com'
paths:
  /version:
    get:
      summary: バージョン情報
      tags:
        - generalInfo
      responses:
        '200':
          description: BCDiceのバージョンとBCDice APIサーバのバージョン
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
      operationId: get-version
      description: BCDiceのバージョンとBCDice APIサーバのバージョンを返します。
  /systems:
    get:
      summary: ゲームシステムID一覧
      tags:
        - generalInfo
      responses:
        '200':
          description: ゲームシステムIDの一覧
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemList'
      operationId: list-systems
      description: ゲームシステムIDの一覧を返します。ゲームシステムIDとは、各ダイスボットが `gameType()` で返す文字列です。
    parameters: []
  /names:
    get:
      summary: ゲームシステムIDとゲームシステム名の一覧
      tags:
        - generalInfo
      responses:
        '200':
          description: ゲームシステムIDとゲームシステム名の一覧
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemIDNameList'
      operationId: get-names
      description: ゲームシステムIDとゲームシステム名の一覧を返します。
    parameters: []
components:
  schemas:
    Version:
      title: Version
      type: object
      description: BCDiceおよびBCDice APIのバージョン情報
      properties:
        bcdice:
          type: string
          description: BCDiceのバージョン
          example: 2.03.04
        api:
          type: string
          example: 1.0.0
          description: BCDice APIサーバのバージョン
      required:
        - bcdice
        - api
    SystemList:
      title: SystemList
      type: object
      description: ゲームシステムIDの一覧
      properties:
        system:
          type: array
          description: ゲームシステムIDの配列
          uniqueItems: true
          items:
            $ref: '#/components/schemas/SystemID'
          example:
            - Amadeus
            - Cthulhu
            - DoubleCross
            - DungeonsAndDoragons
            - DiceBot
            - Gorilla
            - Gundog
            - LogHorizon
            - Nechronica
            - SwordWorld2.0
      required:
        - system
    SystemIDName:
      title: SystemIDName
      type: object
      description: ゲームシステムIDとゲームシステム名の組
      properties:
        system:
          $ref: '#/components/schemas/SystemID'
        name:
          $ref: '#/components/schemas/SystemName'
      required:
        - system
        - name
    SystemIDNameList:
      title: SystemIDNameList
      type: object
      description: ゲームシステムIDとゲームシステム名の一覧
      properties:
        names:
          type: array
          description: ゲームシステムIDとゲームシステム名の組の配列
          items:
            $ref: '#/components/schemas/SystemIDName'
          example:
            - system: Alshard
              name: アルシャード
            - system: Cthulhu
              name: クトゥルフ
            - system: DiceBot
              name: DiceBot
            - system: DoubleCross
              name: 'ダブルクロス2nd,3rd'
            - system: DungeonsAndDoragons
              name: ダンジョンズ＆ドラゴンズ
            - system: Gorilla
              name: ゴリラTRPG
            - system: Gundog
              name: ガンドッグ
            - system: LogHorizon
              name: ログ・ホライズン
            - system: Nechronica
              name: ネクロニカ
            - system: SwordWorld2.0
              name: ソードワールド2.0
      required:
        - names
    SystemID:
      type: string
      title: SystemID
      description: ゲームシステム名
      example: Cthulhu
    SystemName:
      type: string
      title: SystemName
      description: ゲームシステム名
      example: クトゥルフ
tags:
  - name: generalInfo
    description: BCDice全体についての情報
